# QWEN 2.5 Model Fine Tuning

## Meant to be run on Google Colab A100 GPU High RAM

## Dependency Installs

In [ ]:
# Install dependencies
!pip install -q \
  transformers==4.55.4 \
  peft==0.10.0 \
  datasets==3.5.0 \
  accelerate==1.6.0 \
  trl==0.16.1 \
  jedi==0.19.2 \
  torch==2.9.1


!pip uninstall -y torch torchvision torchaudio
!pip install -q torch==2.9.1 torchvision==0.24.1 torchaudio==2.9.1
!pip install -q transformers==4.55.4 accelerate==1.6.0 datasets==3.5.0 peft==0.10.0 trl==0.16.1 safetensors

# Keras (no deps as you had)
!pip install -q tf-keras==2.19.0 --no-dependencies

# DB + env support
!pip install -q \
  sqlalchemy \
  psycopg2-binary \
  python-dotenv

!pip install -U transformers accelerate safetensors

Found existing installation: torch 2.9.1
Uninstalling torch-2.9.1:
  Successfully uninstalled torch-2.9.1
WARNING: Ignoring invalid distribution ~orch (/usr/local/lib/python3.12/dist-packages)
Found existing installation: torchvision 0.25.0+cu128
Uninstalling torchvision-0.25.0+cu128:
  Successfully uninstalled torchvision-0.25.0+cu128
WARNING: Ignoring invalid distribution ~orch (/usr/local/lib/python3.12/dist-packages)
Found existing installation: torchaudio 2.10.0+cu128
Uninstalling torchaudio-2.10.0+cu128:
  Successfully uninstalled torchaudio-2.10.0+cu128
WARNING: Ignoring invalid distribution ~orch (/usr/local/lib/python3.12/dist-packages)
WARNING: Ignoring invalid distribution ~orch (/usr/local/lib/python3.12/dist-packages)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 80.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 109.7 MB/s eta 0:00:00
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.55.4)
Collecting transformers
  Downloading transformers-5.7.0-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.6.0)
Collecting accelerate
  Downloading accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (0.7.0)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers)
  Downloading huggingface_hub-1.13.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.9.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2024.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.5.1)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.7.0-py3-none-any.whl (10.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 125.0 MB/s eta 0:00:00
Downloading accelerate-1.13.0-py3-none-any.whl (383 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.7/383.7 kB 42.8 MB/s eta 0:00:00
Downloading huggingface_hub-1.13.0-py3-none-any.whl (660 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 660.6/660.6 kB 55.6 MB/s eta 0:00:00
Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 124.4 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, tokenizers, accelerate, transformers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 0.36.2
    Uninstalling huggingface_hub-0.36.2:
      Successfully uninstalled huggingface_hub-0.36.2
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.21.4
    Uninstalling tokenizers-0.21.4:
      Successfully uninstalled tokenizers-0.21.4
  Attempting uninstall: accelerate
    Found existing installation: accelerate 1.6.0
    Uninstalling accelerate-1.6.0:
      Successfully uninstalled accelerate-1.6.0
  Attempting uninstall: transformers
    Found existing installation: transformers 4.55.4
    Uninstalling transformers-4.55.4:
      Successfully uninstalled transformers-4.55.4
Successfully installed accelerate-1.13.0 huggingface-hub-1.13.0 tokenizers-0.22.2 transformers-5.7.0

In [ ]:
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError
import pandas as pd
from google.colab import userdata
from datasets import Dataset, DatasetDict
import torch
import psutil
from datasets import ClassLabel
from datasets import concatenate_datasets

In [ ]:
import json
import time
from datetime import datetime

from peft import LoraConfig
from trl import SFTTrainer, SFTConfig

In [ ]:
import torch
import torchvision
import transformers

print(torch.__version__)
print(torchvision.__version__)
print(transformers.__version__)

2.9.1+cu128
0.24.1+cu128
5.7.0

In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Directories

In [ ]:

# Base path
base_dir = "/content/drive/MyDrive/hist_llm_outputs_v2"

# Experiment directories
output_dir_mixed = os.path.join(base_dir, "mixed_sft_lora")
output_dir_curriculum = os.path.join(base_dir, "curriculum_lora")
output_dir_qa_only = os.path.join(base_dir, "qa_only_lora")

# Runtime logs
logpath_mixed = os.path.join(output_dir_mixed, "runtime_log.json")
logpath_curriculum = os.path.join(output_dir_curriculum, "runtime_log.json")
logpath_qa_only = os.path.join(output_dir_qa_only, "runtime_log.json")

# Create directories
os.makedirs(output_dir_mixed, exist_ok=True)
os.makedirs(output_dir_curriculum, exist_ok=True)
os.makedirs(output_dir_qa_only, exist_ok=True)

In [ ]:
DATABASE_URL = userdata.get("DATABASE_URL").strip()

In [ ]:

def check_connection():
  """
  Check if the database connection is working.
  """
  if not DATABASE_URL:
      raise ValueError("DATABASE_URL is not set in .env file")

  try:
      engine = create_engine(DATABASE_URL)

      with engine.connect() as conn:
          result = conn.execute(text("SELECT 1"))
          print("✅ Successfully connected to Neon/Postgres!")

  except SQLAlchemyError as e:
      print("❌ Database connection failed.")
      print(f"Error: {e}")
      engine = None

def load_table_as_dataset(
    engine,
    table_name: str,
    columns: list[str] | None = None,
    where_clause: str | None = None,
    limit: int | None = None,
) -> Dataset:
    """
    Load a Postgres table/query into a Hugging Face Dataset.
    Splitting is handled outside this function.
    """

    selected_columns = ", ".join(columns) if columns else "*"

    query = f"SELECT {selected_columns} FROM {table_name}"

    if where_clause:
        query += f" WHERE {where_clause}"

    if limit:
        query += f" LIMIT {limit}"

    try:
        df = pd.read_sql(text(query), engine)

        if df.empty:
            raise ValueError(f"No rows returned from table: {table_name}")

        return Dataset.from_pandas(df, preserve_index=False)

    except SQLAlchemyError as e:
        raise RuntimeError(f"Database error while loading {table_name}: {e}")

    except Exception as e:
        raise RuntimeError(f"Failed to create dataset from {table_name}: {e}")

### Logging Functions

In [ ]:
def load_stats_log(path):
  if os.path.exists(path):
    with open(path, "r") as f:
      return json.load(f)
  return {"runs": [], "total_seconds": 0.0, "MAX_peak_vram_gb": 0.0}

def save_stats_log(path, data):
  with open(path, "w") as f:
    json.dump(data, f, indent=2)

# LOADING DATA FROM SQL (START)

## Create PostgresSQL

In [ ]:
DATABASE_URL = userdata.get("DATABASE_URL").strip()

In [ ]:
print(DATABASE_URL)
engine = create_engine(DATABASE_URL)

postgresql://neondb_owner:npg_7iGyzKt8InOB@ep-royal-wave-akf0dc1s-pooler.c-3.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require

### Loading in Datasets from PostGresSQL

In [ ]:

qa_dataset = load_table_as_dataset(
    engine=engine,
    table_name="qa_pairs",
    columns=["question", "answer","time_period"],
    where_clause="answer IS NOT NULL"
)

In [ ]:
print(qa_dataset)

Dataset({
    features: ['question', 'answer', 'time_period'],
    num_rows: 2133
})

In [ ]:
bio_dataset = load_table_as_dataset(
    engine=engine,
    table_name="biographies",
    columns=["curid", "name", "biography"]
)

In [ ]:
print(bio_dataset)

Dataset({
    features: ['curid', 'name', 'biography'],
    num_rows: 11341
})

In [ ]:
events_dataset = load_table_as_dataset(
    engine=engine,
    table_name="historical_events",
    columns=["id", "event_name", "day", "month", "year", "country", "event_type", "place_name", "impact", "affected_population", "responsible_entity", "raw_day" ]
  )

In [ ]:
print(events_dataset)

Dataset({
    features: ['id', 'event_name', 'day', 'month', 'year', 'country', 'event_type', 'place_name', 'impact', 'affected_population', 'responsible_entity', 'raw_day'],
    num_rows: 1096
})

# LOADING DATA FROM SQL (END)

# FORMATTING DATA TO SPECIFIC MODEL(START)

## System Prompt

In [ ]:
SYSTEM_PROMPT = (
    "You are a world history expert. Answer historical questions with factual, "
    "accurate, and clear responses. Focus on relevant historical context, key facts, "
    "causes, effects, people, places, and dates when appropriate. If you do not have "
    "enough context, say so rather than inventing details."
)

In [ ]:
model_name = "Qwen/Qwen2-1.5B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

# QWEN 3 Chat Template

In [ ]:
def apply_chat_template(
    data,
    tokenizer,
    system_prompt="",
    user_key="text",
    assistant_key=None,
    label_key=None,
    labels_map=None,
    include_system=True,
    add_generation_prompt=False,
):

    messages = []

    # System message
    if include_system and system_prompt:
        messages.append({
            "role": "system",
            "content": system_prompt,
        })

    # User message
    user_content = data.get(user_key, "")
    messages.append({
        "role": "user",
        "content": user_content,
    })

    # Assistant message (for supervised fine-tuning)
    assistant_content = None

    if assistant_key:
        assistant_content = data.get(assistant_key, "")
    elif label_key and labels_map:
        label_value = data.get(label_key)
        assistant_content = labels_map.get(label_value, "")

    if assistant_content is not None:
        messages.append({
            "role": "assistant",
            "content": assistant_content,
        })

    # Apply tokenizer template
    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=add_generation_prompt,
    )

    return {
        "input_text": prompt,
        "label": assistant_content,
        "original_text": user_content,
    }

# Formatting QA Dataset

In [ ]:
qa_formatted = qa_dataset.map(
    lambda row: apply_chat_template(
        data=row,
        tokenizer=tokenizer,
        system_prompt=SYSTEM_PROMPT,
        user_key="question",
        assistant_key="answer",
    )
)

Map:   0%|          | 0/2133 [00:00<?, ? examples/s]

In [ ]:
class_label = ClassLabel(names=["prehistory_to_1500", "history_after_1500"])

qa_formatted =qa_formatted.cast_column("time_period", class_label)

Casting the dataset:   0%|          | 0/2133 [00:00<?, ? examples/s]

## Formatting Biographies Dataset

In [ ]:
def format_bio_row(row):
    return {
        "instruction": f"Tell me about {row['name']}.",
        "response": row["biography"]
    }

bio_instruction_ds = bio_dataset.map(format_bio_row)

bio_formatted = bio_instruction_ds.map(
    lambda row: apply_chat_template(
        data=row,
        tokenizer=tokenizer,
        system_prompt=SYSTEM_PROMPT,
        user_key="instruction",
        assistant_key="response",
    )
)

Map:   0%|          | 0/11341 [00:00<?, ? examples/s]

Map:   0%|          | 0/11341 [00:00<?, ? examples/s]

#Formatting the Historical Events

In [ ]:
def format_event_row(row):
    user_text = (
        f"Explain the historical event: {row['event_name']}."
    )

    answer_text = (
        f"{row['event_name']} occurred in {row.get('year', 'an unknown year')} "
        f"in {row.get('country', 'an unknown country')}. "
        f"Event type: {row.get('event_type', 'unknown')}. "
        f"Place: {row.get('place_name', 'unknown')}. "
        f"Impact: {row.get('impact', 'not specified')}. "
        f"Affected population: {row.get('affected_population', 'not specified')}. "
        f"Responsible entity: {row.get('responsible_entity', 'not specified')}."
    )

    return {
        "instruction": user_text,
        "response": answer_text
    }

events_instruction_ds = events_dataset.map(format_event_row)

events_formatted = events_instruction_ds.map(
    lambda row: apply_chat_template(
        data=row,
        tokenizer=tokenizer,
        system_prompt=SYSTEM_PROMPT,
        user_key="instruction",
        assistant_key="response",
    )
)

Map:   0%|          | 0/1096 [00:00<?, ? examples/s]

Map:   0%|          | 0/1096 [00:00<?, ? examples/s]

# FORMATTING DATA TO SPECIFIC MODEL(END)

# Enviorment constraints and Model Loading Function (START)

In [ ]:
torch.manual_seed(0)

# Verify GPU Requirements
assert torch.cuda.is_available(), "This tutorial requires a GPU"

total_vram = torch.cuda.get_device_properties(0).total_memory
# assert total_vram > 24 * 1e9, "This tutorial requires a GPU with at least 24GB VRAM"

# Verify RAM requirements
available_ram = psutil.virtual_memory().available
available_swap = psutil.swap_memory().free

if (available_ram + available_swap) < 160 * 1e9:
    print("Warning: Your system has less than 160GB of combined RAM and swap which may cause Out-Of-Memory errors")

Warning: Your system has less than 160GB of combined RAM and swap which may cause Out-Of-Memory errors

In [ ]:
def load_base_model(model_name):
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype="auto",
        device_map="auto",
    )
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    return model, tokenizer

# Enviorment constraints and Model Loading Function (END)

# D: QA-only SFT - Trained only on QA (START)

# Load QWEN 3 1.7B Model

In [ ]:
model_name = "Qwen/Qwen2-1.5B-Instruct"

In [ ]:
model, tokenizer = load_base_model(model_name)

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

In [ ]:
# tokenizer.model_max_length = 512

In [ ]:
split_ds = qa_formatted.train_test_split(test_size=.2,stratify_by_column="time_period", seed=42)

In [ ]:
train_ds = split_ds["train"]
test_ds = split_ds["test"]

In [ ]:
print("TRAIN SIZE:", len(train_ds))
print("TEST SIZE:",len(test_ds))

TRAIN SIZE: 1706
TEST SIZE: 427

In [ ]:
print(train_ds[0])

{'question': 'What are the two primary materials needed to make bronze?', 'answer': 'The two essential elements for producing bronze are **copper** and **tin**. This combination became instrumental for the development of metallurgy in ancient civilizations, especially noted during the early empires like that of the Assyrians. These civilizations placed a strong emphasis on long-distance trade, where Assyrian traders were known to travel extensively to source shipments of these metals, which were often scarce in their homeland. The reliance on both copper and tin underscores the broader theme of resource scarcity in Mesopotamia, and the political implications tied to the control and trade of these vital materials, which shaped diplomatic relations and economic strategies among rival kingdoms.', 'time_period': 0, 'input_text': '<|im_start|>system\nYou are a world history expert. Answer historical questions with factual, accurate, and clear responses. Focus on relevant historical context, key facts, causes, effects, people, places, and dates when appropriate. If you do not have enough context, say so rather than inventing details.<|im_end|>\n<|im_start|>user\nWhat are the two primary materials needed to make bronze?<|im_end|>\n<|im_start|>assistant\nThe two essential elements for producing bronze are **copper** and **tin**. This combination became instrumental for the development of metallurgy in ancient civilizations, especially noted during the early empires like that of the Assyrians. These civilizations placed a strong emphasis on long-distance trade, where Assyrian traders were known to travel extensively to source shipments of these metals, which were often scarce in their homeland. The reliance on both copper and tin underscores the broader theme of resource scarcity in Mesopotamia, and the political implications tied to the control and trade of these vital materials, which shaped diplomatic relations and economic strategies among rival kingdoms.<|im_end|>\n', 'label': 'The two essential elements for producing bronze are **copper** and **tin**. This combination became instrumental for the development of metallurgy in ancient civilizations, especially noted during the early empires like that of the Assyrians. These civilizations placed a strong emphasis on long-distance trade, where Assyrian traders were known to travel extensively to source shipments of these metals, which were often scarce in their homeland. The reliance on both copper and tin underscores the broader theme of resource scarcity in Mesopotamia, and the political implications tied to the control and trade of these vital materials, which shaped diplomatic relations and economic strategies among rival kingdoms.', 'original_text': 'What are the two primary materials needed to make bronze?'}

In [ ]:
print(test_ds[0])

{'question': 'How did Menelik II respond to the Italian invasion during the First Italo-Ethiopian War, and what was the outcome of the conflict?', 'answer': "Emperor Menelik II's response to the Italian invasion was both strategic and resilient, showcasing Ethiopia's capacity for organized resistance. After the Italians invaded in 1895, Menelik II allied with Empress Tatyu Betal and effectively mobilized a diverse army to counter the invaders. The culmination of their military effort was the decisive victory at the Battle of Adwa in March 1896, which resulted in a significant setback for Italy's colonial ambitions. The outcome of the war was formalized in the Treaty of Addis Ababa, wherein Italy acknowledged Ethiopia's sovereignty. This conflict not only preserved Ethiopian independence but also served as a powerful example of African resistance to colonialism during a period characterized by extensive imperial pursuits by European powers.", 'time_period': 1, 'input_text': "<|im_start|>system\nYou are a world history expert. Answer historical questions with factual, accurate, and clear responses. Focus on relevant historical context, key facts, causes, effects, people, places, and dates when appropriate. If you do not have enough context, say so rather than inventing details.<|im_end|>\n<|im_start|>user\nHow did Menelik II respond to the Italian invasion during the First Italo-Ethiopian War, and what was the outcome of the conflict?<|im_end|>\n<|im_start|>assistant\nEmperor Menelik II's response to the Italian invasion was both strategic and resilient, showcasing Ethiopia's capacity for organized resistance. After the Italians invaded in 1895, Menelik II allied with Empress Tatyu Betal and effectively mobilized a diverse army to counter the invaders. The culmination of their military effort was the decisive victory at the Battle of Adwa in March 1896, which resulted in a significant setback for Italy's colonial ambitions. The outcome of the war was formalized in the Treaty of Addis Ababa, wherein Italy acknowledged Ethiopia's sovereignty. This conflict not only preserved Ethiopian independence but also served as a powerful example of African resistance to colonialism during a period characterized by extensive imperial pursuits by European powers.<|im_end|>\n", 'label': "Emperor Menelik II's response to the Italian invasion was both strategic and resilient, showcasing Ethiopia's capacity for organized resistance. After the Italians invaded in 1895, Menelik II allied with Empress Tatyu Betal and effectively mobilized a diverse army to counter the invaders. The culmination of their military effort was the decisive victory at the Battle of Adwa in March 1896, which resulted in a significant setback for Italy's colonial ambitions. The outcome of the war was formalized in the Treaty of Addis Ababa, wherein Italy acknowledged Ethiopia's sovereignty. This conflict not only preserved Ethiopian independence but also served as a powerful example of African resistance to colonialism during a period characterized by extensive imperial pursuits by European powers.", 'original_text': 'How did Menelik II respond to the Italian invasion during the First Italo-Ethiopian War, and what was the outcome of the conflict?'}

# LORA CONFIG

In [ ]:

# =========================
# LoRA Configuration (Hailo-compatible)
# =========================
peft_config = LoraConfig(
    lora_alpha=64,          # Hailo supports 64
    lora_dropout=0.05,
    r=32,                   # Hailo supports up to 32
    task_type="CAUSAL_LM",
    target_modules=[
        "gate_proj",
        "down_proj",
        "up_proj",
    ]  # Hailo currently supports FFN modules only
)


training_args = SFTConfig(
    max_seq_length=512,
    output_dir=output_dir_qa_only,
    num_train_epochs=1,
    per_device_train_batch_size=4,
    logging_steps=50,
    dataset_text_field="input_text",
    save_strategy="steps",
    save_steps=200,
    save_total_limit=3,

)

trainer = SFTTrainer(
    model=model,
    train_dataset=train_ds,
    eval_dataset=test_ds,
    peft_config=peft_config,
    args=training_args,
    processing_class=tokenizer,
)

Converting train dataset to ChatML:   0%|          | 0/1706 [00:00<?, ? examples/s]

Applying chat template to train dataset:   0%|          | 0/1706 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1706 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/1706 [00:00<?, ? examples/s]

Converting eval dataset to ChatML:   0%|          | 0/427 [00:00<?, ? examples/s]

Applying chat template to eval dataset:   0%|          | 0/427 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/427 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/427 [00:00<?, ? examples/s]

In [ ]:
runtime_log1 = load_stats_log(logpath_qa_only)

In [ ]:

torch.cuda.reset_peak_memory_stats()
start = time.time()
start_iso = datetime.now().isoformat()

# Initial Training
train_result = trainer.train()

# Load from checkpoint
#train_result = trainer.train(resume_from_checkpoint=True)

end = time.time()
end_iso = datetime.now().isoformat()
elapsed_time = end - start
peak_vram_gb = torch.cuda.max_memory_allocated() / (1024**3)

entry = {
    "start": start_iso,
    "end": end_iso,
    "elapsed_seconds": elapsed_time,
    "global_step_after_run": int(trainer.state.global_step),
    "peak_vram_gb": peak_vram_gb,
}

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

In [ ]:
runtime_log1["runs"].append(entry)
runtime_log1["total_seconds"] += elapsed_time
runtime_log1["MAX_peak_vram_gb"] = max(runtime_log1["MAX_peak_vram_gb"], peak_vram_gb)

save_stats_log(logpath_qa_only, runtime_log1)

print(f"Current run time: {elapsed_time/60:.2f} min")
print(f"Cumulative training time: {runtime_log1['total_seconds']/3600:.2f} hr")
print(f"Peak VRAM this run: {peak_vram_gb:.2f} GB")
print(f"Max peak VRAM across runs: {runtime_log1['MAX_peak_vram_gb']:.2f} GB")

Current run time: 1.20 min
Cumulative training time: 0.02 hr
Peak VRAM this run: 10.18 GB
Max peak VRAM across runs: 10.18 GB

In [ ]:
trainer.model.save_pretrained(output_dir_qa_only)
tokenizer.save_pretrained(output_dir_qa_only)

('/content/drive/MyDrive/hist_llm_outputs_v2/qa_only_lora/tokenizer_config.json',
 '/content/drive/MyDrive/hist_llm_outputs_v2/qa_only_lora/chat_template.jinja',
 '/content/drive/MyDrive/hist_llm_outputs_v2/qa_only_lora/tokenizer.json')

In [ ]:
# D: QA-only SFT - Trained only on QA (END)

# B: Mixed SFT(BALANCED) - Trained on all datasets together (START)

In [ ]:
model_name = "Qwen/Qwen2-1.5B-Instruct"

In [ ]:
model, tokenizer = load_base_model(model_name)

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

In [ ]:
min_size = min(
    len(qa_formatted),
    len(bio_formatted),
    len(events_formatted),
)

qa_sample = qa_formatted.shuffle(seed=42).select(range(min_size))
bio_sample = bio_formatted.shuffle(seed=42).select(range(min_size))
events_sample = events_formatted.shuffle(seed=42).select(range(min_size))

mixed_dataset = concatenate_datasets([
    qa_sample,
    bio_sample,
    events_sample,
]).shuffle(seed=42)

mixed_split = mixed_dataset.train_test_split(
    test_size=0.2,
    seed=42
)

In [ ]:
mixed_train_ds = mixed_split["train"]
mixed_test_ds = mixed_split["test"]

In [ ]:
training_args_mixed = SFTConfig(
    max_seq_length=512,
    output_dir=output_dir_mixed,
    num_train_epochs=1,
    per_device_train_batch_size=4,
    logging_steps=50,
    dataset_text_field="input_text",
    save_strategy="steps",
    save_steps=200,
    save_total_limit=2,
)

In [ ]:
mixed_trainer = SFTTrainer(
    model=model,
    train_dataset=mixed_train_ds,
    eval_dataset=mixed_test_ds,
    peft_config=peft_config,
    args=training_args_mixed,
    processing_class=tokenizer,
)

Converting train dataset to ChatML:   0%|          | 0/2630 [00:00<?, ? examples/s]

Applying chat template to train dataset:   0%|          | 0/2630 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/2630 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/2630 [00:00<?, ? examples/s]

Converting eval dataset to ChatML:   0%|          | 0/658 [00:00<?, ? examples/s]

Applying chat template to eval dataset:   0%|          | 0/658 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/658 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/658 [00:00<?, ? examples/s]

In [ ]:
runtime_log2 = load_stats_log(logpath_mixed)

In [ ]:
torch.cuda.reset_peak_memory_stats()
start = time.time()
start_iso = datetime.now().isoformat()

# Initial Training
train_result = mixed_trainer.train()

# Load from checkpoint
#train_result = trainer.train(resume_from_checkpoint=True)

end = time.time()
end_iso = datetime.now().isoformat()
elapsed_time = end - start
peak_vram_gb = torch.cuda.max_memory_allocated() / (1024**3)

entry = {
    "start": start_iso,
    "end": end_iso,
    "elapsed_seconds": elapsed_time,
    "global_step_after_run": int(mixed_trainer.state.global_step),
    "peak_vram_gb": peak_vram_gb,
}

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

In [ ]:
runtime_log2["runs"].append(entry)
runtime_log2["total_seconds"] += elapsed_time
runtime_log2["MAX_peak_vram_gb"] = max(runtime_log2["MAX_peak_vram_gb"], peak_vram_gb)

save_stats_log(logpath_mixed, runtime_log2)

print(f"Current run time: {elapsed_time/60:.2f} min")
print(f"Cumulative training time: {runtime_log2['total_seconds']/3600:.2f} hr")
print(f"Peak VRAM this run: {peak_vram_gb:.2f} GB")
print(f"Max peak VRAM across runs: {runtime_log2['MAX_peak_vram_gb']:.2f} GB")

Current run time: 1.95 min
Cumulative training time: 0.03 hr
Peak VRAM this run: 15.82 GB
Max peak VRAM across runs: 15.82 GB

In [ ]:
mixed_trainer.model.save_pretrained(output_dir_mixed)
tokenizer.save_pretrained(output_dir_mixed)

('/content/drive/MyDrive/hist_llm_outputs_v2/mixed_sft_lora/tokenizer_config.json',
 '/content/drive/MyDrive/hist_llm_outputs_v2/mixed_sft_lora/chat_template.jinja',
 '/content/drive/MyDrive/hist_llm_outputs_v2/mixed_sft_lora/tokenizer.json')

# B: Mixed SFT(BALANCED) - Trained on all datasets together (END)

# C: Curriculum SFT - Trained Sequentially(START):

In [ ]:
model_name = "Qwen/Qwen2-1.5B-Instruct"

In [ ]:
model, tokenizer = load_base_model(model_name)

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

In [ ]:
curriculum_stages = [
    ("stage_1_bios", bio_formatted),
    ("stage_2_events", events_formatted),
    ("stage_3_qa", qa_formatted),
]

In [ ]:
runtime_log3 = load_stats_log(logpath_curriculum)

In [ ]:
for stage_name, stage_dataset in curriculum_stages:
    #IMPORTANT FOR NOT REUSING LORA
    peft_for_stage = peft_config if stage_name == "stage_1_bios" else None
    stage_output_dir = os.path.join(output_dir_curriculum, stage_name)

    split = stage_dataset.shuffle(seed=42).train_test_split(
        test_size=0.2,
        seed=42
    )

    stage_args = SFTConfig(
        max_seq_length=512,
        output_dir=stage_output_dir,
        num_train_epochs=1,
        per_device_train_batch_size=4,
        logging_steps=50,
        dataset_text_field="input_text",
        save_strategy="steps",
        save_steps=200,
        save_total_limit=2,
    )

    stage_trainer = SFTTrainer(
        model=model,
        train_dataset=split["train"],
        eval_dataset=split["test"],
        peft_config=peft_for_stage,
        args=stage_args,
        processing_class=tokenizer,
    )

    print(f"Starting curriculum stage: {stage_name}")
    torch.cuda.reset_peak_memory_stats()

    start = time.time()
    start_iso = datetime.now().isoformat()

    stage_trainer.train()


    end = time.time()
    end_iso = datetime.now().isoformat()
    elapsed_time = end - start
    peak_vram_gb = torch.cuda.max_memory_allocated() / (1024**3)


    entry = {
    "stage_name": stage_name,
    "start": start_iso,
    "end": end_iso,
    "elapsed_seconds": elapsed_time,
    "global_step_after_run": int(stage_trainer.state.global_step),
    "peak_vram_gb": peak_vram_gb,
    }

    runtime_log3["runs"].append(entry)
    runtime_log3["total_seconds"] += elapsed_time
    runtime_log3["MAX_peak_vram_gb"] = max(
        runtime_log3["MAX_peak_vram_gb"], peak_vram_gb
    )

    save_stats_log(logpath_curriculum, runtime_log3)

    model = stage_trainer.model

    stage_trainer.model.save_pretrained(stage_output_dir)
    tokenizer.save_pretrained(stage_output_dir)

Converting train dataset to ChatML:   0%|          | 0/9072 [00:00<?, ? examples/s]

Applying chat template to train dataset:   0%|          | 0/9072 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/9072 [00:00<?, ? examples/s]

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (35082 > 32768). Running this sequence through the model will result in indexing errors

Truncating train dataset:   0%|          | 0/9072 [00:00<?, ? examples/s]

Converting eval dataset to ChatML:   0%|          | 0/2269 [00:00<?, ? examples/s]

Applying chat template to eval dataset:   0%|          | 0/2269 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/2269 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/2269 [00:00<?, ? examples/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

Starting curriculum stage: stage_1_bios

Converting train dataset to ChatML:   0%|          | 0/876 [00:00<?, ? examples/s]

Applying chat template to train dataset:   0%|          | 0/876 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/876 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/876 [00:00<?, ? examples/s]

Converting eval dataset to ChatML:   0%|          | 0/220 [00:00<?, ? examples/s]

Applying chat template to eval dataset:   0%|          | 0/220 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/220 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/220 [00:00<?, ? examples/s]

Starting curriculum stage: stage_2_events

Converting train dataset to ChatML:   0%|          | 0/1706 [00:00<?, ? examples/s]

Applying chat template to train dataset:   0%|          | 0/1706 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1706 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/1706 [00:00<?, ? examples/s]

Converting eval dataset to ChatML:   0%|          | 0/427 [00:00<?, ? examples/s]

Applying chat template to eval dataset:   0%|          | 0/427 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/427 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/427 [00:00<?, ? examples/s]

Starting curriculum stage: stage_3_qa

In [ ]:
model.save_pretrained(output_dir_curriculum)
tokenizer.save_pretrained(output_dir_curriculum)

('/content/drive/MyDrive/hist_llm_outputs_v2/curriculum_lora/tokenizer_config.json',
 '/content/drive/MyDrive/hist_llm_outputs_v2/curriculum_lora/chat_template.jinja',
 '/content/drive/MyDrive/hist_llm_outputs_v2/curriculum_lora/tokenizer.json')

# C: Curriculum SFT - Trained Sequentially(END):